FROM registry.access.redhat.com/ubi8/python-312

WORKDIR /opt/app-root

COPY . /opt/app-root

USER root

RUN dnf -y update && dnf install -y gcc gcc-c++ \
 && pip install uv

ENV UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    VIRTUAL_ENV=/opt/app-root/.venv \
    PATH="/opt/app-root/.venv/bin:$PATH"

RUN --mount=type=cache,target=/.cache/uv \
    uv sync --frozen --no-install-project --no-dev

RUN --mount=type=cache,target=/.cache/uv \
    uv sync --frozen --no-dev

RUN chgrp -R root /opt/app-root/ && chmod -R g+rwx /opt/app-root/

EXPOSE 10001

USER 1001

CMD uv run app --host weather-agent
